[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=0"

[[redirects]]
  from = "/apple-app-site-association"
  to = "/.well-known/apple-app-site-association"
  status = 200
  force = true