[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-store"

[[redirects]]
  from = "/apple-app-site-association"
  to = "/.well-known/apple-app-site-association"
  status = 200
  force = true

[[headers]]
  for = "/.well-known/assetLinks.json"
  [headers.values]
    Content-Type = "application/json"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-store"

[[redirects]]
  from = "/assetLinks.json"
  to = "/.well-known/assetLinks.json"
  status = 200
  force = true